# Generated by Django 5.0 on 2023-12-11 02:15

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_corta', models.CharField(max_length=500)),
                ('descripcion_larga', models.CharField(max_length=1000)),
                ('valor', models.IntegerField()),
                ('necesita_receta', models.BooleanField(default=False)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_categoria',
            fields=[
                ('producto_categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.categoria')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(related_name='productos', through='producto.Producto_categoria', to='producto.categoria'),
        ),
    ]
