# Generated by Django 5.0 on 2023-12-25 22:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('valor', models.IntegerField()),
                ('necesita_receta', models.BooleanField(default=False)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('categoria', models.ManyToManyField(related_name='productos_categoria', to='producto.categoria')),
            ],
        ),
    ]
