# Generated by Django 5.0 on 2023-12-25 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='tipo_convenio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.categoria_convenio'),
        ),
    ]
