# Generated by Django 5.0 on 2023-12-28 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='convenio',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
