# Generated by Django 5.0 on 2023-12-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_convenio_tipo_convenio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='especialista',
            field=models.ManyToManyField(related_name='convenios_especialista', to='servicio.especialista'),
        ),
    ]
