# Generated by Django 5.0 on 2023-12-28 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_consulta_fecha_creacion_convenio_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 1, 59, 16, 891999, tzinfo=datetime.timezone.utc)),
        ),
    ]
