# Generated by Django 5.0 on 2023-12-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_convenio_especialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='especialista',
            field=models.ManyToManyField(related_name='especialidades_especialistas', to='servicio.especialista'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='servicios',
            field=models.ManyToManyField(related_name='especialidades_servicios', to='servicio.servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='especialidades',
            field=models.ManyToManyField(related_name='servicios_especialidades', to='servicio.especialidad'),
        ),
    ]
