# Generated by Django 5.0 on 2023-12-28 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_consulta_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
