# Generated by Django 5.0 on 2023-12-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_especialidad_especialista_especialidad_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='especialista',
            field=models.ManyToManyField(blank=True, related_name='convenios_especialista', to='servicio.especialista'),
        ),
    ]
