# Generated by Django 5.0 on 2023-12-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_alter_convenio_especialista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='especialista',
            field=models.ManyToManyField(blank=True, related_name='especialidades_especialistas', to='servicio.especialista'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='especialidades_servicios', to='servicio.servicio'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='convenio',
            field=models.ManyToManyField(blank=True, related_name='especialista_convenio', to='servicio.convenio'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='especialidad',
            field=models.ManyToManyField(blank=True, related_name='especialista_especialidad', to='servicio.especialidad'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='servicios_especialidades', to='servicio.especialidad'),
        ),
    ]
