# Generated by Django 5.0 on 2023-12-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_especialidad_especialista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='especialidades',
        ),
    ]
